/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SalesOrderDeliveryListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheSalesOrderDeliveryListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheSalesOrderDeliveryListGenerated.onFilterBar().iCheckFilterField({ property: "SalesOrder" });
            Then.onTheSalesOrderDeliveryListGenerated.onFilterBar().iCheckFilterField({ property: "SalesOrganization" });
            Then.onTheSalesOrderDeliveryListGenerated.onFilterBar().iCheckFilterField({ property: "SoldToParty" });
            Then.onTheSalesOrderDeliveryListGenerated.onFilterBar().iCheckFilterField({ property: "SalesOrderDate" });
            Then.onTheSalesOrderDeliveryListGenerated.onFilterBar().iCheckFilterField({ property: "Material" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheSalesOrderDeliveryListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheSalesOrderDeliveryListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheSalesOrderDeliveryListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheSalesOrderDeliveryListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"SalesOrder":{"header":"销售订单"},"SalesOrderItem":{"header":"销售订单明细"},"SalesOrganization":{"header":"销售组织"},"SalesOrderDate":{"header":"受注日"},"SoldToParty":{"header":"得意先"},"CustomerName":{"header":"得意先名称"},"Material":{"header":"物料"},"OrderQuantity":{"header":"受注数量"},"SalesUnit":{"header":"销售单位"},"ScheduleLineDate":{"header":"纳入日程日"},"DeliveryDocument":{"header":"出荷番号"},"ActualGoodsMovementDate":{"header":"实际出库日"},"DeliveryStatus":{"header":"出荷状态"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheSalesOrderDeliveryListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheSalesOrderDeliveryListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheSalesOrderDeliveryListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheSalesOrderDeliveryObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});